# Generated by Django 4.0.2 on 2022-05-01 20:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer_registration',
            fields=[
                ('farmer_id', models.AutoField(primary_key=True, serialize=False)),
                ('farmer_name', models.CharField(max_length=50)),
                ('farmer_address', models.CharField(max_length=50)),
                ('farmer_phone', models.CharField(max_length=10)),
                ('farmer_email', models.EmailField(max_length=50)),
                ('farmer_password', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 2, 2, 20, 10, 636522))),
            ],
            options={
                'db_table': 'Farmer',
            },
        ),
    ]
