# Generated by Django 4.0.5 on 2022-06-17 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_otp_alter_farmer_registration_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer_registration',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 18, 0, 0, 53, 549018)),
        ),
    ]
