# Generated by Django 4.0.5 on 2022-06-24 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_alter_farmer_registration_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_Id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('product_category', models.CharField(max_length=50)),
                ('product_price', models.CharField(max_length=50)),
                ('product_offer', models.CharField(max_length=50)),
                ('product_brand', models.CharField(max_length=50)),
                ('product_description', models.CharField(max_length=100000)),
                ('product_img', models.ImageField(upload_to='images')),
                ('stock_size', models.IntegerField(default=2)),
            ],
            options={
                'db_table': 'Products',
            },
        ),
        migrations.AlterField(
            model_name='farmer_registration',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 25, 1, 49, 8, 299549)),
        ),
    ]
