# Generated by Django 4.0.5 on 2022-06-26 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0004_products_alter_farmer_registration_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer_registration',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 26, 17, 36, 33, 313729)),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_img',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='products',
            name='stock_size',
            field=models.IntegerField(default=1),
        ),
    ]
