# Generated by Django 4.0.5 on 2022-06-27 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0005_alter_farmer_registration_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer_registration',
            name='farmer_img',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farmer_registration',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 27, 11, 23, 37, 181687)),
        ),
    ]
