# Generated by Django 4.0.5 on 2022-06-27 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0006_farmer_registration_farmer_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer_registration',
            name='account_type',
            field=models.CharField(default='admin', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farmer_registration',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 27, 11, 51, 7, 94433)),
        ),
        migrations.AlterField(
            model_name='farmer_registration',
            name='farmer_address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='farmer_registration',
            name='farmer_phone',
            field=models.CharField(max_length=50),
        ),
    ]
