# Generated by Django 4.0.5 on 2022-06-29 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0007_farmer_registration_account_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('farmer_id', models.CharField(max_length=50)),
                ('product_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 30, 0, 45, 27, 535011))),
            ],
            options={
                'db_table': 'Cart',
            },
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('wishList_id', models.AutoField(primary_key=True, serialize=False)),
                ('farmer_id', models.CharField(max_length=50)),
                ('product_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 30, 0, 45, 27, 535011))),
            ],
            options={
                'db_table': 'WishList',
            },
        ),
        migrations.AlterField(
            model_name='farmer_registration',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 30, 0, 45, 27, 535011)),
        ),
    ]
