# Generated by Django 4.0.5 on 2022-06-30 15:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0010_alter_cart_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='temp',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 30, 15, 48, 14, 616932, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='farmer_registration',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 30, 15, 48, 14, 615432, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 30, 15, 48, 14, 616432, tzinfo=utc)),
        ),
    ]
