# Generated by Django 4.0.5 on 2022-06-30 15:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0011_wishlist_temp_alter_cart_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 30, 15, 52, 34, 34893, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='farmer_registration',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 30, 15, 52, 34, 33383, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 30, 15, 52, 34, 34384, tzinfo=utc)),
        ),
    ]
