# Generated by Django 4.0.5 on 2022-06-30 16:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0012_alter_cart_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='temp',
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 30, 16, 30, 42, 922701, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='farmer_registration',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 30, 16, 30, 42, 922701, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 30, 16, 30, 42, 922701, tzinfo=utc)),
        ),
    ]
