# Generated by Django 4.0.5 on 2022-07-01 19:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0013_remove_wishlist_temp_alter_cart_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_content', models.CharField(max_length=500)),
                ('sender_id', models.CharField(max_length=500)),
                ('receiver_id', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 1, 19, 36, 1, 263472, tzinfo=utc))),
            ],
            options={
                'db_table': 'Chat',
            },
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 1, 19, 36, 1, 262886, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='farmer_registration',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 1, 19, 36, 1, 260248, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 1, 19, 36, 1, 262176, tzinfo=utc)),
        ),
    ]
