# Generated by Django 4.0.5 on 2022-07-12 07:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0015_auth_alter_cart_created_at_alter_chat_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_added_by',
            field=models.CharField(default='Admin', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='product_added_by_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 12, 7, 39, 1, 955661, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 12, 7, 39, 1, 955661, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='farmer_registration',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 12, 7, 39, 1, 947202, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 12, 7, 39, 1, 955661, tzinfo=utc)),
        ),
    ]
