# Generated by Django 4.0.5 on 2022-09-18 18:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0016_products_product_added_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_category', models.CharField(max_length=50)),
                ('product_price', models.CharField(max_length=50)),
                ('product_added_by_id', models.CharField(max_length=50)),
                ('product_added_by', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 18, 18, 0, 1, 298811, tzinfo=utc))),
            ],
            options={
                'db_table': 'Purches',
            },
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 18, 18, 0, 1, 293794, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 18, 18, 0, 1, 293794, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='farmer_registration',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 18, 18, 0, 1, 293794, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 18, 18, 0, 1, 293794, tzinfo=utc)),
        ),
    ]
